spring:
  datasource:
    url: jdbc:h2:mem:ranieris_credit_application_db
    username: ranieriiuri
    # password: apikotlin |--> Caso queira
  jpa:
    show-sql?: true
    hibernate:
      properties:
        hibernate.format_sql: true
      # ddl-auto: create-drop |--> Caso fosse ordenar p criar (qnd subir) e destruir (qnd parasse a execução) as tabelas
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
